name: Build and Deploy Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python my_script.py